---
# tasks file for ssh_config
- name: writing ssh config
  become: '{{ ssh_config_privilege_elevate }}'
  become_user: root
  template:
    src: config.j2
    dest: '{{ ssh_config_target }}'
    mode: '400'
